[package]
name = "sqlite-python"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite-loadable = {path="../sqlite-loadable-rs"}
serde_json = "1.0.89"

[dependencies.pyo3]
version = "0.17.3"
features = ["auto-initialize"]

[lib]
crate-type=["rlib", "cdylib"]
name = "py0"